version: "3.9"

services:
    db:
        image: postgres
        hostname: postgresql
        container_name: postgres_nest
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_db:/var/lib/postgresql/data
        env_file:
            - .env
        networks:
            - nest_net

    redis_notify:
        build:
            context: .
            dockerfile: Dockerfile.redis
        restart: always
        container_name: redis_nest
        hostname: redishost
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - nest_net

volumes:
    postgres_db:
    redis_data:

networks:
    nest_net:

